# Generated by Django 3.1 on 2020-08-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200826_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
